# Simple test makefile
EMUNIT_DIR = ../..
EMUNIT_PORT = pcstdout
EXTRAINCDIRS = c:/code/simavr_dist/include

TARGET = $(EMUNIT_PORT)_simple
SRC = main.c
F_CPU = 4000000

# Include building system
include $(EMUNIT_DIR)/emunit.mk
