# Simple test makefile
EMUNIT_DIR = ../..
EMUNIT_PORT = simavr
EXTRAINCDIRS = c:/code/simavr_dist/include

TARGET = simple
SRC = main.c
F_CPU = 4000000

# Include building system
include $(EMUNIT_DIR)/emunit.mk
