# Simple test makefile
EMUNIT_DIR = ../..
EMUNIT_PORT = pctest

TARGET = $(EMUNIT_PORT)_simple
SRC = \
	suites.c \
	main.c \
	test_boolean.c \
	test_equal.c

# Include building system
include $(EMUNIT_DIR)/emunit.mk
